### ISSUE TITLE
How to create pages that do not require authentication (Landing Page)

### ISSUE THREAD

**Issue by cyberautomate** [creativetimofficial/ct-soft-ui-dashboard-pro-laravel#1]
I have the Laravel Pro version of this template. Home can I make basic pages with the Navbar that do not require a user to login? Similar to a landing page.

I cannot find an example in the installation files.

**Comment by teamupdivision** [comment]
Hello,

Thank you for using Creative TIM products!

You can create the Controller and blade the normal way but the route needs to be added in the web.php file in the guest group not the auth. 

Thank you.

**Comment by cyberautomate** [comment]
So, I copied the default.blade.php in the dashboards folder. I renamed it to srd.blade.php. I commented out all the included routes and added only one for my sdr dashboard ```Route::view('/', 'dashboards/srd');```
In my srd view I changed this 
```@extends('user_type.auth', ['parentFolder' => 'dashboards', 'childFolder' => 'none'])``` 
to 
```@extends('user_type.guest', ['parentFolder' => 'dashboards', 'childFolder' => 'none'])```

That seems to work without the authentication requirement. The only problem is the navigation bar is gone. How do I add the navbar to the view?

**Comment by teamupdivision** [comment]
Hello,

Please first check and see the app.blade.php file structure where you can see it has different components based on the type of user (authenticated or unauthenticated). 

Then in the user_type folder in the guest.blade.php file you can see the components that are used for the unauthenticated users, and you can modify your structure there.

 Also check the register and login controllers and blade files as examples of pages that allow guest users. 
 
 Thank you.
