### ISSUE TITLE
Database Seeding problem

### ISSUE THREAD

**Issue by ThatGuyJop** [creativetimofficial/ct-soft-ui-dashboard-pro-laravel#2]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

I expect that the database seed would import needed tables to the database.

# Current Behavior

What is the current behavior?

The seeding of the table 'users' is not working because there are 2 same files in the migrations folder. And I dont know which one to pick.

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.
`PHP Fatal error:  Cannot declare class CreateUsersTable, because the name is already in use in C:\Users\jopte\InfinitCAD\database\migrations\2021_06_05_000000_create_users_table.php on line 7`

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Install newest version on the creative-tim website.
2. Setup laravel etc.
3. once you are on the step where you need to seed the database migrations it gives the error.
4. 
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: Laptop
* Operating System: Windows 10
* Browser and Version: Mozilla Firefox newest version

Im new to Laravel and bought this product to learn it, I dont know if i setup laravel correctly but this seems like a migration fault not my setup fault.

## Failure Logs

Please include any relevant log snippets or files here.
![image](https://user-images.githubusercontent.com/45967788/132683495-5ad8b7e1-c00c-4148-a831-9b3e7dd33e8a.png)

**Comment by ThatGuyJop** [comment]
![image](https://user-images.githubusercontent.com/45967788/132683720-d9efd9c0-a243-4e78-8af1-7631c87906d7.png)
 
 Forgot this image

**Comment by teamupdivision** [comment]
Hi @ThatGuyJop,

Thank you for reporting this issue and for using Creative Tim products.

We tried to follow the same steps in a similar context, but we were not able to reproduce the error. We were thinking this was caused by one of the migrations that were added afterward. Could you try removing the migration that was not initially in the project or follow the initial setup process from readme/documentation one more time? 

Please let us know if this helped. 
 
All the best,
UPDIVISION Team

**Comment by ThatGuyJop** [comment]
Just downloaded it again, and I don't see any duplicated user table migrations.
Thanks for giving support anyways and sorry for taking your time.

**Comment by teamupdivision** [comment]
Hi @ThatGuyJop,

Thank you very much for the update. In case there is any other issue or information we can help with, please feel free to let us know. 

Best,
UPDIVISION Team

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).
