### ISSUE TITLE
Changing Colors

### ISSUE THREAD

**Issue by cyberautomate** [creativetimofficial/ct-soft-ui-dashboard-pro-laravel#2]
With the Laravel template, what is the preferred method for changing the default color palette? What files should I update or create to make sure my changes are not overwritten by a future update of the template?

**Comment by rarestoma** [comment]
Hi @cyberautomate,

Thank you for working with our products.

You need to change the colors available in this folder: `public/assets/scss/soft-ui-dashboard/_variables.scss`.

Please let me know if it works.

Regards,
Rares
