### ISSUE TITLE
Can't compile SASS

### ISSUE THREAD

**Issue by ThisIsPita** [creativetimofficial/ct-soft-ui-dashboard-pro-laravel#3]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

To compile included SASS files.

# Current Behavior

Errors. First error encountered is below. If fixed by declaring the variable there are more undefined variable errors later in the compilation. I have tried with Laravel Mix and Node Sass. There was no gulp file included to try to compile with Gulp.

{
  "status": 1,
  "file": "C:/laragon/www/ctiretailers/resources/scss/soft-ui-dashboard/variables/_choices.scss",
  "line": 4,
  "column": 22,
  "message": "Undefined variable: \"$dropdown-transition\".",
  "formatted": "Error: Undefined variable: \"$dropdown-transition\".\n        on line 4 of resources/scss/soft-ui-dashboard/variables/_choices.scss\n
from line 14 of resources/scss/soft-ui-dashboard/_variables-extend.scss\n        from line 8 of resources/scss/soft-ui-dashboard.scss\n>> $choices-transition: $dropdown-transition !default;\n\n   ---------------------^\n"
}

**Comment by teamupdivision** [comment]
Hi @ThisIsPita,

Thanks for reporting this issue and for using Creative Tim products. 

Would you be able to send a few more details on the steps followed with Laravel Mix and Node Saas, please? What is the node version used? Also if you could send to us a recording or a few screenshots, this may also help a lot. 

Let us know.

Best,
UPDIVISION Team

**Comment by ThisIsPita** [comment]
Hello,

Thank you for your help. I am including a 2 part screenshot of the Mix build and one of the node-sass build. Also a screenshot of node and node-sass versions. Finally below is the webpack.mix.js command.

mix.sass('resources/scss/soft-ui-dashboard.scss', 'public/assets/css/new/soft-ui-dashboard2.css'

![mix-part1](https://user-images.githubusercontent.com/3780978/140408228-35a6c6f9-63aa-4d5b-8865-30b522ea663e.png)
![mix-part2](https://user-images.githubusercontent.com/3780978/140408230-85299313-8701-47aa-9332-80a6faa577d6.png)
![node-sass](https://user-images.githubusercontent.com/3780978/140408232-6bd9f209-880e-4b9d-a4cb-3bf928489c5d.png)
![versions](https://user-images.githubusercontent.com/3780978/140408234-a32f1f78-e72d-4517-86ab-7737ca2492a9.png)
);

**Comment by ThisIsPita** [comment]
@teamupdivision Any updates for me?

**Comment by teamupdivision** [comment]
Hi @ThisIsPita,

Thank you very much for sharing the additional details! This helped a lot in investigating further. We'll get back with the updates very shortly. 

Best,
UPDIVISION Team

**Comment by teamupdivision** [comment]
Hi @ThisIsPita,

Thanks again for reporting this issue and for using Creative Tim products.

We've pushed a fix to this problem.
You can access it by downloading the product from the downloads section on the Creative Tim website.

You may either reinstall the project or download the sass folder and replace the old one with this. Please also check the webpack mix and then npm run dev.

Please let us know if everything works as expected or if you have any other issues. 

All the best,
UPDIVISION Team

**Comment by ThisIsPita** [comment]
It compiles properly now and everything look good when using the newly compiled CSS.

Thanks @teamupdivision

**Comment by cristinad2** [comment]
Hi Antonio,

We're glad to hear that. In case there are any other issues, please feel
free to contact us anytime.

Best,
Cristina

**Comment by teamupdivision** [comment]
Hi Antonio, 

We're glad to hear that. In case there are any other issues, please feel free to contact us anytime.

Best,
UPDIVISION Team
