### ISSUE TITLE
Error at php artisan migrate --seed

### ISSUE THREAD

**Issue by yukeshean** [creativetimofficial/ct-soft-ui-dashboard-pro-laravel#4]
>php artisan migrate --seed

Migration table created successfully.
Migrating: 2014_10_12_100000_create_password_resets_table

   Illuminate\Database\QueryException

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter table `password_resets` add index `password_resets_email_index`(`email`))

**Comment by teamupdivision** [comment]
Hello @yukeshean, thanks for using Creative Tim products!
You are probably using Windows and you are new to Laravel.

Please refer to this small fix you need to do: https://stackoverflow.com/questions/42244541/laravel-migration-error-syntax-error-or-access-violation-1071-specified-key-wa
