### ISSUE TITLE
Side nav bar is not behaving correctly.

### ISSUE THREAD

**Issue by win4dk** [creativetimofficial/ct-soft-ui-dashboard-pro-laravel#5]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting.
When I resize my windows to the smallest, the navbar should disappear.

# Current Behavior

What is the current behavior?
When I resize my windows to the smallest, the navbar is overlapping part of the screen. Sometimes, it will be transparent and make a mess in the display.

**Comment by teamupdivision** [comment]
Hello @win4dk,

Thanks for using Creative Tim products.
Can you please tell us more about your system, what is the operating system and the browser you are testing on?

Thank you

**Comment by win4dk** [comment]
I am using macOS Monterey. The browser is Safari 15.1

**Comment by teamupdivision** [comment]
Hi @win4dk,

Thank you very much. We're working on this issue for this version of Safari and we'll get back with an update shortly. 

Best,
UPDIVISION Team

**Comment by teamupdivision** [comment]
Hi @win4dk,

Thanks again for reporting this issue and for using Creative Tim products.
We've pushed a fix to this problem.

You can access it by downloading the product from the downloads section in the Creative Tim website.

Please let us know if you have any other issues.

All the best,
UPDIVISION Team

**Comment by teamupdivision** [comment]
Hi there @win4dk, 

We would like to check if the issue was solved and if there is anything else we can help with. 
Please let us know if you have any other issues. 

All the best,
Updivision Team

**Comment by teamupdivision** [comment]
Hi @win4dk,

Hope this solved the problem. We will go ahead and close this ticket. If there is anything else we can help with, please let us know.

Best,
UPDIVISION Team

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).
